defaults: &DEFAULTS

development:
  <<: *DEFAULTS

  token_life_time: 14   # token有效期为14天
  
  valid_response: 0x0
  params_error: 0x1
  token_error: 0x2

  signup: { 
    ok: { code: 0x0, message: "注册成功" },
    error: { code: 0x1, message: "该用户名已注册" }
  }
  
  login: {
    ok: { code: 0x0, message: "登录成功" },
    error: { code: 0x1, message: "用户名或密码错误" }
  }

  logout: { 
    ok: { code: 0x0, message: "注销成功" }
  }

  change_password: {
    ok: { code: 0x0, message: "密码设置成功" },
    error: { code: 0x1, message: "原密码错误" }
  }

  get_avatar: { 
    ok: { code: 0x0, message: "O(∩_∩)O~" },
    error: { code: 0x1, message: "头像获取失败" }
  }

  change_avatar: {
    ok: { code: 0x0, message: "头像更换成功" },
    error: { code: 0x1, message: "来个小一点的图片呗~" }
  }

  check_data: {
    ok: { code: 0x0, message: "同步检查完毕" },
    error: { code: 0x1, message: "遇到一些问题" }
  }
      
  push_data: {
    ok: { code: 0x0, message: "上传数据完毕" },
    error: { code: 0x1, message: "遇到一些问题" }
  }

  pull_data: {
    ok: { code: 0x0, message: "下载数据完毕" },
    error: { code: 0x1, message: "遇到一些问题" }
  }
  
  sync_data: {
    ok: { code: 0x0, message: "同步数据完毕" },
    error: { code: 0x1, message: "遇到一些问题" }
  }
  
  avatar_str_limit: 10_485_760    # 头像Base64编码字符串长度不能超过10M

production:
  <<: *DEFAULTS
  token_life_time: 14

test:
  <<: *DEFAULTS
  token_life_time: 14