development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gamma_dev
  host: 
  pool: 5
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gamma_pro
  host: 
  pool: 5
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gamma_test
  host: 
  pool: 5
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock
